-- Adds a per-file delete authorization token, separate from the public file
-- ID. The file ID is necessarily shared (it's embedded in the CDN URL /
-- GET endpoint), so it must not double as a delete credential. Only the
-- SHA-256 hash of the token is stored, matching how uploader IPs are
-- handled elsewhere - the plaintext token is returned to the uploader
-- exactly once, in the upload response, and never persisted or logged.
--
-- This file intentionally contains no SQL. Both the "delete_token_hash"
-- column and its index are created in Go by
-- SQLiteRepository.Migrate()/ensureColumn() (see repository.go), not here:
--
--   1. "ALTER TABLE ... ADD COLUMN IF NOT EXISTS" requires SQLite 3.35+,
--      which isn't guaranteed across every go-sqlite3 build (this is what
--      broke here originally - see git history).
--   2. Migrate() has no applied-migrations tracking table - it re-runs
--      every *.sql file in this directory on every process startup, so a
--      plain "ALTER TABLE ADD COLUMN" would fail on the second startup
--      once the column already exists.
--   3. The index needs the column to exist first, which means it can't be
--      plain SQL executed in the same file-list pass as 0001_init.sql
--      (which only creates the table) without introducing an ordering
--      dependency between migration files that this runner doesn't model.
--
-- Kept as an empty (comment-only) file rather than deleted, to preserve
-- the historical migration sequence and the intent it documents.
